"""
This is a setup.py script generated by py2applet

Usage:
python3 setup.py py2app # note NOT python but python3
"""

from setuptools import setup  # got a depr alert from this setuptools

APP = ['Game.py']
DATA_FILES = ['icon.icns']
# OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    # options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    options=dict(py2app=dict(
        plist='Info.plist',
    )),
)
